version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rental_system
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "3001:3001"
      - "5555:5555"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend

volumes:
  mysql-data: